# golangci-lint configuration v2
# https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m
  tests: true
  build-tags:
    - fts5

linters:
  enable:
    - govet # 官方静态分析
    - errcheck # 错误检查
    - staticcheck # 综合静态分析 (包含 gosimple, unused)
    - ineffassign # 无效赋值检测
    - misspell # 拼写检查
    - gocyclo # 圈复杂度检查
    - gocritic # 代码质量建议
  settings:
    gocritic:
      disabled-checks:
        - unlambda # 不强制将 lambda 替换为函数引用
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - dupl
      - path: internal/graph/generated/
        linters:
          - all

formatters:
  enable:
    - gofumpt
    - goimports
